name: Automated tests # придумать название наших тестов

on: # запускать тест в ситуации
#  push
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true  # говорит про то что мы ждем выбора пользователя что он хочет запустить
        default:
        type: choice
        options:
          - first_test
          - second_test
          - all_test

jobs: # наши джобы, можем прописывать тесты по отдельности
  test:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt

      - name: first_test
        if: "github.event.deployment_target == 'first_test'"
        run: pytest tests/test_button.py::test_button_exist

      - name: second_test
        if: "github.event.deployment_target == 'second_test'"
        run: pytest tests/test_button.py::test_button_exist_2

      - name: all_test
        run: pytest

